[package]
name = "stevedore"
version = "0.1.0"
description = "Docker distribution for Windows that Just Works"
edition = "2021"
authors = ["Marat Radchenko <marat@slonopotamus.org>"]
homepage = "https://github.com/slonopotamus/stevedore"
repository = "https://github.com/slonopotamus/stevedore.git"
license = "Apache-2.0"

[dependencies]
directories = "4.0"
msgbox = "0.7"
named-lock = "0.1"
trayicon = { version = "0.1", features = ["winit"] }
winapi = { version = "0.3" }
winit = "0.25"
wslapi = "0.1"

[build-dependencies]
bytes = "1.1"
const_format = "0.2"
flate2 = "1"
reqwest = { version = "0.11", features = ["blocking"] }
sha2 = "0.10"
winres = "0.1"
zip = "0.5"
